spring:
  application:
    name: cyberlab-site

  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    open-in-view: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: ${DB_SCHEMA}
    liquibase-schema: ${DB_SCHEMA}

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  address: 0.0.0.0
  port: 8080
